version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ./.env
    
  backend:
    image: ./backend/
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    env_file: .env

  frontend:
    env_file: .env
    image: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
