version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    
  backend:
    image: nadia1983/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/

  frontend:
    env_file: .env
    image: nadia1983/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: nadia1983/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
