version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    
  backend:
    image: nadia1983/kittygram_backend
    env_file: .env
    volumes:

      #- static:/app/backend_static/
      - static:/backend_static
      - media:/media/

  frontend:
    env_file: .env
    image: nadia1983/kittygram_frontend
    # command: cp -r /app/build/. /static/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      #- static:/static
      - static:/frontend_static

  gateway:
    image: nadia1983/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      #- static:/static
      - static:/staticfiles
      - media:/media
